### ISSUE TITLE
tagged release?

### ISSUE THREAD

**Issue by dmiddlecamp** [steamroller-airmash/airmash-server#122]
I'd like to pull a version of this repo and build a new image to throw online for FFA, but I'm not sure where to cut the release...  Would someone be able to cut a release at a stable commit for purposes of deploying to prod? :)

**Comment by steamroller-airmash** [comment]
I can definitely tag a release if you want :) 

However, since the development process of this repo is currently more of a (somewhat) continuous stream of refactoring/bugfixes any release will be about as arbitrary as just taking the current state in master at a point in time. I've tried to keep master in a releasable state although I'll admit that currently CI is not anywhere near thorough enough to stake my reputation on that.

If you have any advice on how to determine when enough changes have accumulated to be "release-worthy" I'd love to hear it! One possibility is to just create a patch release every time master is updated but that seems to be missing the point.

From my point of view it would be ideal to have everyone following master. However, I acknowledge that that's a lot of effort and the infrastructure that's set up isn't good enough for realistic continuous delivery so it's probably unreasonable to expect that.

I'll tag a release off of master tomorrow since I'm still working on some changes.

**Comment by steamroller-airmash** [comment]
Alright, I've created release [v0.0.1](https://github.com/steamroller-airmash/airmash-server/releases/tag/v0.0.1) for you :)

Would still appreciate input on how to determine what constitutes enough work for a release.
