### ISSUE TITLE
Space-time trap

### ISSUE THREAD

**Issue by usopp-airmash** [steamroller-airmash/airmash-server#123]
Banmeplz (and some other guys) found out today in ctf that you can do the following in the top left corner.

- Use a goli to push another plane (with 1 push) into the corner. The next position of the pushed plane is the coordinate origin (0,0) at Sahara. The pushed plane can't no longer escape by moving around and must respawn.
- An opponent flag can be taken in this space time trap. If you get a flag in there when you respawn you still have the flag.

Perhaps, it might help to explain why missile, shield images are not deleted.

**Comment by steamroller-airmash** [comment]
I've been able to reproduce this with all 4 corners so it's not just something that happens in the top-left corner.

I suspect that the root cause is that both the client and server consider (0, 0) to be a marker that the player is spectating. However, this doesn't explain why it happens at all 4 corners.

I can definitely patch this over and that should be good enough.

**Comment by usopp-airmash** [comment]
We also observed the ghost missile effects inside the trap, see reddit post. Perhaps it wouldn't be worthwhile to investigate it before fixing the bug. 
There's one more thing. When you fly to the SE corner, you would experience a massive ping delay and waves of ghost missiles, similar to the one inside the trap.
