### ISSUE TITLE
Missiles fired before spawn are not displayed

### ISSUE THREAD

**Issue by mpnordland** [steamroller-airmash/airmash-server#73]
## Steps to reproduce
Open two Airmash windows to the same server and game. Use one plane to destroy the other. 
Watch on the destroyed plane's window and keep firing from the other.
You should see hits but no missiles being fired. 

## Expected behavior
Missles are rendered.

**Comment by steamroller-airmash** [comment]
Here's some notes for anyone who wants to tackle this issue (I'm not going to have time until later this week at the earliest):

The root cause of this issue is that currently the server only sends missile updates when they are fired. This works ok most of the time, but when the player doesn't get the initial firing message the client will never know that the missile exists.

The proper solution is to create a new handler for `PlayerJoin` events (put it in `server/src/systems/handlers/game/on_join`) that does the following:
- Sends a [`MobUpdate`](https://docs.rs/airmash-protocol/0.2.6/airmash_protocol/server/struct.MobUpdate.html) packet to the client for all missiles within viewing distance. (`types::Config` has a viewing distance that should be used for this)
- Runs *after* the system that sends the login response packet (the client will ignore any packets it receives before the login response). This means that the new system will have to depend on `systems::handlers::game::on_join::SendLogin`.
- Must be registered in `server/src/handlers/game/register.rs` otherwise the new system won't be run.

It is worth looking at the other join event handlers to get an idea of how they are structured.
