### ISSUE TITLE
Boosting with predator causes jitter

### ISSUE THREAD

**Issue by steamroller-airmash** [steamroller-airmash/airmash-server#89]
## Summary
Tapping shift while flying a plane causes the plane to "jump". This is probably similar to #82.

## Steps to Reproduce
1. Fly a predator
2. Go forward while tapping shift repeatedly
3. The plane should start jumping in small amounts when shift is pressed

**Comment by derps-airmash** [comment]
*[moved from #83.. stupid GitHub login redirect]*

No solution, but maybe some hints from the client side. Given:

````javascript
i=setInterval(function() { console.log(game.jitter); }, 500)
````

It:

- falls to zero when flying away from all other players (no server packets arriving?)
- looks like a very good estimate of ping when sitting idle near other players (lots of packets arriving?)
- quickly falls to zero when pressing keys (including secondary) while near other players (???)

It seems jitter should not fall to zero when pressing keys. Perhaps the server does not reproduce some subtlety of the clock field, or perhaps the clock field isn't being serialized correctly?

I cleaned up Network.js by renaming all the related variables so the client logic is more obvious, e.g.  https://github.com/derps-airmash/airmash-frontend/blob/220029361af7248e335f5403516db7c94a2b8e52/js/Network.js#L157-L182

The `game.jitter` variable is used by `Tools.reducedFactor()` to produced a smudged "current time" according to the current ping. That function is in turn used by Mob and `Player.update()` to ultimately set the position

**Comment by derps-airmash** [comment]
https://github.com/derps-airmash/airmash-server/commit/4933ff97c1253eefe25a9ed701493a2b324c09b1 :D :D

game.jitter value drops from something that looks like the ping measured in microseconds.. to the ping measured in milliseconds.

pred movement seems almost spotless now, but maybe this is confirmation bias. there might be a little jank left in it, but i'm fairly certain this is much improved

![](https://i.imgflip.com/330p72.jpg)

**Comment by derps-airmash** [comment]
from reading the bits of Network.js related to `game.jitter`, it seems if that is the only use of clock, then it should be stamped as close to packet transmission time as possible (i.e. ideally on the packet sender thread to avoid scheduler nondeterminism).

The key points are:

### LOGIN

On login,

````
                    baseDivClk = msg.clock / 100;
                    baseDivClkLastResetTime = performance.now();
````

We save some reference value of the clock along with a local timestamp


### dispatchIncomingMessage

If packet contains a clock,

````
                        resetJitterMemoryEvery5Mins(curPacketDivClk);
                        var curTime = game.timeNetwork;
                        var delta = (curPacketDivClk - baseDivClk) - (curTime - baseDivClkLastResetTime);
                        var newJitter = delta - (jitterMemory = (.8 * jitterMemory) + (delta / 5));
                        if(Math.abs(newJitter) < 100) {
                            game.jitter = newJitter;
                        }
````

We reset our reference every 5 minutes in case I guess network conditions have improved(?)

Otherwise compare the reference server clock with most recent packet clock, and subtract that from reference clock local timestamp and current timestamp, giving a milliseconds +/- delta of how early/late the packet is with respect to the reference packet.

Take (I think?) a moving average (or something like it) of the past 5 samples and use that as the jitter estimate. If the estimate exceeds +/- 100ms then assume the measurement is garbage and perform no correction at all.

I think the jank was due to (for whatever reason, still not clear) when smashing keys causing one of those branches to reset jitter down to zero, any previous reducedFactor() in effect using the 1000x incorrect values would suddenly be undone

**Comment by steamroller-airmash** [comment]
Nice work! Let's get these changes upstreamed :)

**Comment by derps-airmash** [comment]
I need to rebase to yours and test out with whatever compiler version master moved to, then carve the patches up and document them properly

Main worry about compiler is that airmash-client and friends stop building. I'm still a rust noob :)
